include::../config/Environment.adoc[]
ifdef::backend-pdf[<<<]

== API NOTIFICATIONS

For every single of operation on the entities use the following
templates and provide sample REST notification POST calls.

It is assumed that the Pub/Sub uses the Register and UnRegister
mechanisms described in the REST Guidelines reproduced below.

=== Register listener

*POST /hub*

*Description*

Sets the communication endpoint address the service instance must use to
deliver information about its health state, execution state, failures
and metrics. Subsequent POST calls will be rejected by the service if it
does not support multiple listeners. In this case DELETE /api/hub/\{id}
must be called before an endpoint can be created again.

*Behavior*

Returns HTTP/1.1 status code 204 if the request was successful.

Returns HTTP/1.1 status code 409 if request is not successful.

*Usage Samples*

Here's an example of a request for registering a listener.

*Request*

[code]
----
POST /api/hub

Accept: application/json

{
    "callback": "http://in.listener.com"
}
----

*Response*

[code]
----
201

Content-Type: application/json

Location: /api/hub/42

{
    "id":"42",
    "callback": "http://in.listener.com",
    "query":""
}
----

=== Unregister listener

*DELETE /hub/\{id}*

*Description*

Clears the communication endpoint address that was set by creating the
Hub..

*Behavior*

Returns HTTP/1.1 status code 204 if the request was successful.

Returns HTTP/1.1 status code 404 if the resource is not found.

*Usage Samples*

Here's an example of a request for un-registering a listener.


*Request*

[code]
----
DELETE /api/hub/42

Accept: application/json
----

*Response*

[code]
----
204
----

=== Publish Event to listener

*POST /client/listener*

*Description*

Clears the communication endpoint address that was set by creating the
Hub.

Provides to a registered listener the description of the event that was
raised. The /client/listener url is the callback url passed when
registering the listener.

*Behavior*

Returns HTTP/1.1 status code 201 if the service is able to set the
configuration.

*Usage Samples*

Here's an example of a notification received by the listener. In this
example “EVENT TYPE” should be replaced by one of the notification types
supported by this API (see Notification resources Models section) and
EVENT BODY refers to the data structure of the given notification type.

*Request*

[code]
----
POST /client/listener

Accept: application/json

{
    "event": {
        EVENT BODY
    },
    "eventType": "EVENT_TYPE"
}
----

*Response*

[code]
----
201
----

For detailed examples on the general TM Forum notification mechanism,
see the TMF REST Design Guidelines.
