
==  API Operations Conformance

For every single resource the following tables includes mandatory operations.

include::../generated/ResourceMandatoryOperations.adoc[]

== API GET OPERATION CONFORMANCE

All the GET operations in this API share the same status code pattern.

[cols=",",options="header",]
|===
|GET |Mandatory/Optional
|Response Status Code 200 if successful |M
|Response Status Code 404 if not found |M
|===

=== Definitions for Filter

The following definitions apply to all the GET operations:

* {blank}
+
____
Filtered Search: A filtered search can be applied using query parameters to obtain only the resources that meet the criteria defined by the filtering parameters included in the query request. Several elements can be applied to the filtered search. In that case logic, a logical AND is applied to combine the criteria (e.g.:?severity=<value>&status=<value>).
____
* {blank}
+
____
Attribute selection (Limiting Response Data): In order to limit which attributes are included in the response, the GET request can include the ?fields= query parameter. Only those attributes whose names are supplied in this parameter will be returned. Attribute selection capabilities are the same for collections retrieval and individual resource queries.
____
* {blank}
+
____
Level: The filtering and attribute selection can apply to the top level properties (attributes) and subproperties. The tables below show which attributes need to be supported in top-level or contained resources.
____

INSERT-GET-RESOURCE-OPERATION-CONFORMANCE

== API POST OPERATION CONFORMANCE

All the POST operations in this API share the same status code pattern.

[cols=",",options="header",]
|===
|POST |Mandatory/Optional
|Status Code 201 if resource created |M
|===

INSERT-POST-RESOURCE-OPERATION-CONFORMANCE

== API PUT OPERATION CONFORMANCE

All the PUT operations in this API share the same status code pattern.

[cols=",",options="header",]
|===
|PUT |Mandatory/Optional
|Status Code 201 if resource modified |M
|===

INSERT-PUT-RESOURCE-OPERATION-CONFORMANCE

== API PATCH OPERATION CONFORMANCE

All the PATCH operations in this API share the same status code pattern.

The mandatory application context is JSON Merge.

[cols=",",options="header",]
|===
|PATCH |Mandatory/Optional
|Status Code 200 if resource modified |M
|===

INSERT-PATCH-RESOURCE-OPERATION-CONFORMANCE

== API DELETE OPERATION CONFORMANCE

All the DELETE operations in this API share the same status code pattern.

[cols=",",options="header",]
|===
|DELETE |Mandatory/Optional
|Status Code 204 if resource deleted |M
|===

INSERT-DELETE-RESOURCE-OPERATION-CONFORMANCE

== ACKNOWLEDGEMENTS

=== Release History

[cols=",,,",]
|===
|*Release Number* |*Date* |*Release led by:* |*Description*
| | | |
| | | |
|===

=== Version History

[cols=",,,",]
|===
|*Version Number* |*Date* |*Modified by* |*Description*
| | | |
| | | |
|===
