include::../config/Environment.adoc[]
ifdef::backend-pdf[<<<]

== API GET Operation Conformance

All the GET operations in this API share the same status code pattern.

[cols=",",options="header",]
|===
|GET |Mandatory/Optional
|Response Status Code 200 if successful |M
|Response Status Code 404 if not found |M
|===

=== Definitions for Filter

The following definitions apply to all the GET operations:

* {blank}
Filtered Search: A filtered search can be applied using query parameters to obtain only the resources that meet the criteria defined by the filtering parameters included in the query request. Several elements can be applied to the filtered search. In that case logic, a logical AND is applied to combine the criteria (e.g.:?severity=<value>&status=<value>).
* {blank}* {blank}
Attribute selection (Limiting Response Data): In order to limit which attributes are included in the response, the GET request can include the ?fields= query parameter. Only those attributes whose names are supplied in this parameter will be returned. Attribute selection capabilities are the same for collections retrieval and individual resource queries.
* {blank}
Level: The filtering and attribute selection can apply to the top level properties (attributes) and subproperties. The tables below show which attributes need to be supported in top-level or contained resources.


include::../{generated}/GetOperationConformance.adoc[]

