name: Java CI

on: [push]

env:
  APP: oastooling
  ARTIFACT_NAME: 'oastooling.tgz'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v1
                   
       - name: Set up JDK 11
         uses: actions/setup-java@v1
         with:
           java-version: 1.11
       
       - name: OpenAPItools - Build with Maven
         env:
            USER_NAME: ${{ secrets.REPO_USER_NAME }}
            ACCESS_TOKEN: ${{ secrets.REPO_TOKEN }}
         run: |
            mvn install --settings=settings.xml
 
       - name: OpenAPItools - Copy the resulting jar
         run: |
           ls -l
           mkdir -p tooling
           cp target/${APP}*.jar tooling/${APP}.jar 
            
       - name: Combine artifacts
         run: |
           tar -czvf ${{ env.ARTIFACT_NAME }} tooling
    
       - name: Upload Artifacts
         uses: actions/upload-artifact@master
         with:
           name: ${{ env.ARTIFACT_NAME }}
           path: ${{ env.ARTIFACT_NAME }}
  
  test:
    runs-on: ubuntu-latest
    name: test
    needs: [build]
    steps:       
       - name: Download Artifacts
         uses: actions/download-artifact@master
         with:
           name: ${{ env.ARTIFACT_NAME }}
           path: ./

       - name: Test strategy
         run: |
           echo "Testing - to be added"
 
  package:
    runs-on: ubuntu-latest
    name: publish package
    needs: [test]
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode deploy --settings=settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          USER_NAME: ${{ secrets.REPO_USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.REPO_TOKEN }}
